version: '2'

services:

  mysql:
    build: ./mysql
    hostname: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=adminpass
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=demodb
    ports:
      - "3309:3306"

  catalog:
    build: ./catalog
    hostname: catalog
    links:
      - mysql:mysql
    depends_on:
      - mysql
    ports:
      - "3311:3002"