apiVersion: v1
kind: Service
metadata:
  name: mysqlorders
spec:
  ports:
    - port: 3306
  selector:
    app: mysqlorders
  clusterIP: None
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mysqlorders
spec:
  selector:
    matchLabels:
      app: mysqlorders
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: mysqlorders
    spec:
      containers:
        - name: mysql
          image: diebar/mysqlorders:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "adminpass"
            - name: MYSQL_ALLOW_EMPTY_PASSWORD
              value: "true"
          args: ["--default-authentication-plugin=mysql_native_password"]
          ports:
            - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders.fullname" . }}
  labels:
    {{- include "orders.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "orders.selectorLabels" . | nindent 4 }}
